# Generated by Django 3.1.12 on 2022-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0005_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(db_index=True, max_length=100)),
                ('validity_date_start', models.DateTimeField(auto_now_add=True)),
                ('validity_date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'catégories'},
        ),
    ]
