version: "3.9"
services:
  api-plateform:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8110
    networks:
      - api-plateform
  nginx-plateform:
    image: nginx
    # build: ./frontend/doorphone
    # container_name: nginx-plateform
    # restart: "no"
    depends_on:
      - api-plateform
    ports:
      - 8080:8080
      - 4600:4600
    networks:
      - api-plateform
    volumes:
      - ./nginx/conf.d/plateform.conf:/etc/nginx/conf.d/plateform.conf
      - ./log/:/var/log/nginx/
      - ./frontend/doorphone/dist/library:/var/www/angular-deploy


networks:
  api-plateform:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
# sudo iptables -I INPUT 1 -s 172.22.0.0/20 -j ACCEPT
